# The certificate/private key pairs used here was generated via openssl using the
# scripts 'gen_ca.sh' and 'gen_certs.sh' located in the `private/` subdirectory.
#
# The certificates are self-signed. As such, you will need to trust them directly
# for your browser to refer to the connection as secure. You should NEVER use
# these certificate/key pairs. They are here for DEMONSTRATION PURPOSES ONLY.
[default.tls]
certs = "private/rsa_sha256_cert.pem"
key = "private/rsa_sha256_key.pem"

[rsa_sha256.tls]
certs = "private/rsa_sha256_cert.pem"
key = "private/rsa_sha256_key.pem"
[ecdsa_nistp256_sha256.tls]
certs = "private/ecdsa_nistp256_sha256_cert.pem"
key = "private/ecdsa_nistp256_sha256_key_pkcs8.pem"

[ecdsa_nistp384_sha384.tls]
certs = "private/ecdsa_nistp384_sha384_cert.pem"
key = "private/ecdsa_nistp384_sha384_key_pkcs8.pem"

[ed25519.tls]
certs = "private/ed25519_cert.pem"
key = "private/ed25519_key.pem"
