environment:
  matrix:
    - TARGET: nightly-x86_64-pc-windows-msvc
    - TARGET: nightly-i686-pc-windows-msvc
    - TARGET: nightly-x86_64-pc-windows-gnu
    - TARGET: nightly-i686-pc-windows-gnu

# Install Rust and Cargo
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin;C:\Users\appveyor\.cargo\bin"
  - rustc -Vv
  - cargo -V

# Disable Appveyor's build stage. This prevents the "directory does not contain
# a project or solution file" error
build: false

# Equivalent to Travis' `script` phase
test_script:
  - sh "./scripts/test.sh"

branches:
  only:
    - master
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger
    # deploys when a new tag is pushed. This regex matches semantic versions
    # like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+\.\d+.*$/
