[package]
name = "optional_result"
version = "0.0.1"
authors = ["Sergio Benitez <sb@sergio.bz>"]
workspace = "../../"

[dependencies]
rocket = { path = "../../lib" }
rocket_codegen = { path = "../../codegen" }

[dev-dependencies]
rocket = { path = "../../lib", features = ["testing"] }
