[package]
name = "pastebin"
version = "0.0.0"
workspace = "../../"

[dependencies]
rocket = { path = "../../lib" }
rocket_codegen = { path = "../../codegen" }
rand = "0.3"

[dev-dependencies]
rocket = { path = "../../lib", features = ["testing"] }
