[package]
name = "json"
version = "0.0.1"
workspace = "../../"

[dependencies]
rocket = { path = "../../lib" }
rocket_codegen = { path = "../../codegen" }
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"

[dependencies.rocket_contrib]
path = "../../contrib"
default-features = false
features = ["json"]

[dev-dependencies]
rocket = { path = "../../lib", features = ["testing"] }
